### ISSUE TITLE
Remote Schema Resolver should be set with the form `{mod, fun}`

### ISSUE THREAD

**Issue by DavidAntaramian** [jonasschmidt/ex_json_schema#15]
Ran into an issue with a coworker using this library. The problem is the library expects the remote schema resolver to be defined as an anonymous function in the application configuration; however, when compiling distribution releases using Erlang release tooling, this type of configuration value is unsupported. Instead, the schema resolver setting should accept accept a value of the form `{mod, fun_name}` which then calls, `apply(mod, fun_name, [url])`, using a function already present in the codebase. Open to other ideas.

**Comment by jonasschmidt** [comment]
Yes, a very good point, I haven't actually tested this with releases. It should be quite easy to implement this without breaking existing code. As an alternative way of providing the resolver function.

I will fix this early next week. Or you can provide a PR if you have the time.

**Comment by jonasschmidt** [comment]
Fixed in https://github.com/jonasschmidt/ex_json_schema/commit/abf758336aafd7fdcdd6e4da8a66bd0d34c451cf and available in the `v0.5.4` release.

**Comment by DavidAntaramian** [comment]
Thanks so much!
