### ISSUE TITLE
`const` support

### ISSUE THREAD

**Issue by Hu13er** [jonasschmidt/ex_json_schema#35]
Hi!

I guess there's a problem with validator because as it was described in the documention, an instance validates successfully against `const` keyword if its value is equal to the value of the keyword, but it seems like it's not working here.

to say more precisely, the validator doesn't care about `const` existance and it returns true for every value as input.

for example, isn't it a case that it should return false here?

```Elixir
> ExJsonSchema.Schema.resolve(%{"type" => "string", "const" => "foo"})
  |> ExJsonSchema.Validator.valid?("bar")
true
```

Thank you so much

**Comment by jonasschmidt** [comment]
I will keep this issue open until the Draft 6/7 support is officially released.

**Comment by jonasschmidt** [comment]
Actually, `const` is just a more readable form of a one-element enum. So you can get the same behaviour with Draft 4, just the error messages will not be as nice.

**Comment by jonasschmidt** [comment]
Closing because `const` is available with drafts `6`/`7` which are supported now.
