### ISSUE TITLE
Lowercase 'T' and 'Z' in date-time format

### ISSUE THREAD

**Issue by Siyfion** [jonasschmidt/ex_json_schema#39]
So I have a schema which uses the `date-time` format setting.

Given an input `2019-02-28T10:08:30.000Z` `ExJsonSchema.Validator.validate` returns `:ok`.
Given an input `2019-02-28t10:08:30.000z` `ExJsonSchema.Validator.validate` returns `{:error, [{"Expected \"2019-02-28t10:08:30.000z\" to be a valid ISO 8601 date-time.", "#/requestTimestamp"}]}`.

RFC 3339 states that this is valid syntax https://tools.ietf.org/html/rfc3339#section-5.6.

And JSON Schema Test Suite has the following test for this:

https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/c17161a919e92c24cbee08e829ab445fbd4f44b6/tests/draft4/optional/format.json#L41-L45

**Comment by jonasschmidt** [comment]
Yes, good catch. I didn't want to add Timex just for this one small date/time-related thing, that's why it's a regex: https://github.com/jonasschmidt/ex_json_schema/blob/master/lib/ex_json_schema/validator/format.ex#L4

I will fix it and push a new version today.

**Comment by jonasschmidt** [comment]
I haven't updated to the latest version of the official test suite because there were some issues with refs and changing the resolution scope that I need to look into. I will give that another try.

**Comment by Siyfion** [comment]
No problem, just glad that I’ve been able to help find a bug and that it’s an easy fix! 👍🏻

**Comment by jonasschmidt** [comment]
Ok, I updated to the latest version of the test suite so the case is covered that way. The fix is in version `0.5.8` that I just released.
