### ISSUE TITLE
IO.inspect in hex package

### ISSUE THREAD

**Issue by Manzanit0** [jonasschmidt/ex_json_schema#54]
We found there is a `IO.inspect` in the code pushed to hex somewhere in the lib. We can't know where since it's not in Github.

In case it helps, we run it through: https://diff.jola.dev/diff/ex_json_schema/0.7.1/0.7.2 and we found it was in the formatter.

Thanks

**Comment by shdblowers** [comment]
The `IO.inspect` is here:

`ex_json_schema/lib/ex_json_schema/validator/format.ex:28`

**Comment by jonasschmidt** [comment]
Oh wow. It seems like some version that's not even in Git got pushed to Hex as `0.7.2`. I retired the package and pushed a new `0.7.3` version.

The approach of manually pushing the package to Hex might not be a such a good idea. I will look into publishing the package from Travis, and also adding something like Credo to make sure no debug statements can't slip through.

Thanks for catching that issue! 🙇
