### ISSUE TITLE
Examples on usage

### ISSUE THREAD

**Issue by lornatumuhairwe** [jonasschmidt/ex_json_schema#56]
The json schema validation is really great!

I had some trouble writing a schema for validation. The current documentation didn't guide me well. After a while.. I finally got it down but I think it can be better. 

I would like to write a few examples and stick them in the current README, if it's okay. I think it would make it easier for other people that come across it. 

What do you think? Or are there docs I'm missing somewhere?

cc @jonasschmidt

**Comment by lornatumuhairwe** [comment]
Wrote some examples [in this gist](https://gist.github.com/lornatumuhairwe/2778b8936b3f250923d6b20a4a0b63d4) incase someone runs into this.

**Comment by jonasschmidt** [comment]
Thank you for the feedback. Since the lack of documentation seems to be more about JSON Schema in general and not this library in particular, maybe linking to some online resources on how to write and validate a JSON Schema might be a better solution?

**Comment by lornatumuhairwe** [comment]
Thank you for the response. That's will be great! 

I found [this page](http://www.cpan.org/modules/by-module/JSON/JSON-Schema-AsType-0.4.2.readme) that lists all the compliant implementations. The [ruby implementation](https://github.com/ruby-json-schema/json-schema#advanced-options) has good examples. 
[This tutorial](https://ryanbigg.com/2016/11/validating-nested-json-data-with-ex_json_schema) too was also great has a great example in elixir

Do you have any resources in mind?
