### ISSUE TITLE
Elixir 1.11 deprecations

### ISSUE THREAD

**Issue by technomage** [jonasschmidt/ex_json_schema#62]
warning: Map.take/2 with an Enumerable of keys that is not a list is deprecated.  Use a list of keys instead.
  (elixir 1.11.4) lib/map.ex:413: Map.take/2
  (ex_json_schema 0.5.8) lib/ex_json_schema/validator/properties.ex:12: ExJsonSchema.Validator.Properties.validate/3
  (elixir 1.11.4) lib/enum.ex:1075: anonymous fn/3 in Enum.flat_map/2
  (stdlib 3.14.1) maps.erl:233: :maps.fold_1/3
  (elixir 1.11.4) lib/enum.ex:2209: Enum.flat_map/2
  (ex_json_schema 0.5.8) lib/ex_json_schema/validator.ex:28: ExJsonSchema.Validator.validate/4
  (elixir 1.11.4) lib/enum.ex:1075: anonymous fn/3 in Enum.flat_map/2
  (stdlib 3.14.1) maps.erl:233: :maps.fold_1/3
  (elixir 1.11.4) lib/enum.ex:2209: Enum.flat_map/2
  (ex_json_schema 0.5.8) lib/ex_json_schema/validator.ex:28: ExJsonSchema.Validator.validate/4
  (elixir 1.11.4) lib/enum.ex:1075: anonymous fn/3 in Enum.flat_map/2
  (stdlib 3.14.1) maps.erl:233: :maps.fold_1/3
  (elixir 1.11.4) lib/enum.ex:2209: Enum.flat_map/2
  (ex_json_schema 0.5.8) lib/ex_json_schema/validator/properties.ex:9: ExJsonSchema.Validator.Properties.validate/3
  (elixir 1.11.4) lib/enum.ex:1075: anonymous fn/3 in Enum.flat_map/2
  (stdlib 3.14.1) maps.erl:233: :maps.fold_1/3
  (elixir 1.11.4) lib/enum.ex:2209: Enum.flat_map/2
  (ex_json_schema 0.5.8) lib/ex_json_schema/validator.ex:28: ExJsonSchema.Validator.validate/4

**Comment by jonasschmidt** [comment]
Which version of the library is that? The deprecation should already be fixed in `0.8.0-rc1`.
