### ISSUE TITLE
Handling refs in a schema

### ISSUE THREAD

**Issue by Teifion** [jonasschmidt/ex_json_schema#82]
I'm trying to import a schema from a decoded object but I'm hitting errors.

Here is the json file
```json
[
  {
    "$id": "user",
    "type": "object",
    "properties": {
      "id": {
        "minimum": 0,
        "description": "Unique Identifier for this user",
        "examples": [
          1234
        ],
        "type": "integer"
      },
      "name": {
        "minLength": 2,
        "maxLength": 20,
        "pattern": "^[A-Za-z0-9_]+$",
        "type": "string"
      }
    },
    "required": [
      "id",
      "name"
    ]
  },
  {
    "$id": "privateUser",
    "allOf": [
      {
        "$ref": "user"
      },
      {
        "type": "object",
        "properties": {
          "permissions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "permissions"
        ]
      }
    ]
  }
]
```

I started by trying this:
```elixir
File.read!("schemas.json") |> Jason.decode! |> ExJsonSchema.Schema.resolve
```
Unfortunately this errors, presumably because it's a list of schemas. My next try was to break them into a list and handle each of them in turn:
```elixir
      "schemas.json"
      |> File.read!
      |> Jason.decode!
      |> Enum.map(fn json_def ->
        ExJsonSchema.Schema.resolve(json_def)
      end)
```
This chokes on the `privateUser` entry but only if the `"$ref": "user"` part was there.

Obviously the ref isn't known to the library at the time so I'm trying to work out what I should be doing.

Cheers for any assistance you can give.

**Comment by jonasschmidt** [comment]
Hey, if you need help with creating a valid schema with references, there are resources on https://json-schema.org/ that should get you started. The schema you are referencing here is not valid (you can also check with online validators like https://www.jsonschemavalidator.net/ but they won't give you different results).

**Comment by Jazcash** [comment]
I'm working with @Teifion on this, and our use case is that we have a bunch of individual JSONSchemas that describe different request and response endpoints for our API, rather than the entire API being one big JSONSchema file itself. Some of these requests and response schemas share refs to other schemas, but we don't know if it's possible for this library to load schemas with refs to previously loaded schemas.

I'm working on the client side of things using Typescirpt and AJV (JSONSchema validator), and I can supply an array of schemas and it will resolve the refs to other schemas.

```typescript
const ajv = new Ajv({
    schemas: [
        {
            '$id': 'address',
            type: 'object',
            properties: { line_1: { type: 'string' }, line_2: { type: 'string' } },
            required: [ 'line_1', 'line_2' ]
        },
        {
            '$id': 'person',
            type: 'object',
            properties: { name: { type: 'string' }, address: { '$ref': 'address' } },
            required: [ 'name', 'address' ]
        }
    ]
});

const validator = ajv.getSchema("person");
```

Is something like this possible for elixir using this lib?

**Comment by jonasschmidt** [comment]
Ah ok, that's a library-specific feature not defined in the standard that this library doesn't support. JSON Schema supports ways of bundling multiple schemas as described here though: http://json-schema.org/understanding-json-schema/structuring.html#bundling
